classdef PlotReferenceBuilder
    %PLOTREFERENCEBUILDER Builds force-target annotations for live plots.

    methods (Static)
        %% Preview construction and target grouping
        function preview = build(selectedTab, config, axisMode, hwConfig)
            % Build entries only for active axes and force-controlled endpoints.
            preview = struct( ...
                'testType', '', ...
                'X', PlotReferenceBuilder.emptyEntries(), ...
                'Y', PlotReferenceBuilder.emptyEntries());
            selectedTab = char(selectedTab);
            axes = TestCommandBuilder.axesForMode(axisMode);

            switch selectedTab
                case 'Pre-test'
                    preview.testType = 'pre';
                    for index = 1:numel(axes)
                        axis = axes{index};
                        field = lower(axis);
                        entries = PlotReferenceBuilder.emptyEntries();
                        [tolerancePercent, minTolerance] = ...
                            PlotReferenceBuilder.toleranceSettings( ...
                            config.pre.forceTolerance.(field), ...
                            hwConfig, field);
                        if config.pre.preload.enabled
                            entries(end + 1) = ...
                                PlotReferenceBuilder.entry( ...
                                'Pre-test', 'Initial preload', ...
                                'preload', ...
                                config.pre.preload.value.(field), ...
                                tolerancePercent, minTolerance);%#ok<AGROW>
                        end
                        if config.pre.cyclic
                            entries(end + 1) = ...
                                PlotReferenceBuilder.entry( ...
                                'Pre-test', 'Pre-cycle load', ...
                                'load', config.pre.load.(field), ...
                                tolerancePercent, minTolerance);%#ok<AGROW>
                            if ~config.pre.unloadToStart
                                entries(end + 1) = ...
                                    PlotReferenceBuilder.entry( ...
                                    'Pre-test', 'Pre-cycle unload', ...
                                    'unload', ...
                                    config.pre.unload.(field), ...
                                    tolerancePercent, minTolerance);%#ok<AGROW>
                            end
                        end
                        preview.(axis) = entries;
                    end

                case 'Single test'
                    preview.testType = 'single';
                    for index = 1:numel(axes)
                        axis = axes{index};
                        field = lower(axis);
                        entries = PlotReferenceBuilder.emptyEntries();
                        [tolerancePercent, minTolerance] = ...
                            PlotReferenceBuilder.toleranceSettings( ...
                            config.single.forceTolerance.(field), ...
                            hwConfig, field);
                        if strcmp(config.single.primaryMode, 'Force')
                            entries(end + 1) = ...
                                PlotReferenceBuilder.entry( ...
                                'Single test', 'Primary endpoint', ...
                                'primary', ...
                                config.single.primary.(field), ...
                                tolerancePercent, minTolerance);%#ok<AGROW>
                        end
                        if ~config.single.rupture.enabled && ...
                                strcmp(config.single.secondaryMode, 'Force')
                            entries(end + 1) = ...
                                PlotReferenceBuilder.entry( ...
                                'Single test', 'Secondary endpoint', ...
                                'secondary', ...
                                config.single.secondary.(field), ...
                                tolerancePercent, minTolerance);%#ok<AGROW>
                        end
                        preview.(axis) = entries;
                    end

                case 'Cyclic test'
                    preview.testType = 'cyclic';
                    for index = 1:numel(axes)
                        axis = axes{index};
                        field = lower(axis);
                        entries = PlotReferenceBuilder.emptyEntries();
                        [tolerancePercent, minTolerance] = ...
                            PlotReferenceBuilder.toleranceSettings( ...
                            config.cyclic.forceTolerance.(field), ...
                            hwConfig, field);
                        if strcmp(config.cyclic.loadMode, 'Force')
                            entries(end + 1) = ...
                                PlotReferenceBuilder.entry( ...
                                'Cyclic test', 'Load endpoint', ...
                                'load', ...
                                config.cyclic.load.(field), ...
                                tolerancePercent, minTolerance);%#ok<AGROW>
                        end
                        if strcmp(config.cyclic.unloadMode, 'Force')
                            entries(end + 1) = ...
                                PlotReferenceBuilder.entry( ...
                                'Cyclic test', 'Unload endpoint', ...
                                'unload', ...
                                config.cyclic.unload.(field), ...
                                tolerancePercent, minTolerance);%#ok<AGROW>
                        end
                        preview.(axis) = entries;
                    end
            end
        end

        function grouped = group(entries)
            % Merge identical bands while retaining every endpoint label.
            grouped = PlotReferenceBuilder.emptyEntries();
            for index = 1:numel(entries)
                entry = entries(index);
                match = [];
                for candidate = 1:numel(grouped)
                    if grouped(candidate).target == entry.target && ...
                            grouped(candidate).tolerance == entry.tolerance
                        match = candidate;
                        break;
                    end
                end
                if isempty(match)
                    grouped(end + 1) = entry;%#ok<AGROW>
                elseif ~contains( ...
                        [' / ', grouped(match).label, ' / '], ...
                        [' / ', entry.label, ' / '])
                    grouped(match).label = ...
                        [grouped(match).label, ' / ', entry.label];
                end
            end
        end

        function entries = emptyEntries()
            % Keep a stable empty schema so callers can concatenate entries.
            entries = struct( ...
                'phase', {}, 'label', {}, 'role', {}, ...
                'target', {}, 'tolerance', {}, ...
                'tolerancePercent', {}, 'minimumTolerance', {});
        end
    end

    methods (Static, Access = private)
        %% Entry construction
        function value = entry( ...
                phase, label, role, target, tolerancePercent, minTolerance)
            tolerance = max(abs(double(target)) * ...
                double(tolerancePercent) / 100, double(minTolerance));
            value = struct( ...
                'phase', char(phase), ...
                'label', char(label), ...
                'role', char(role), ...
                'target', double(target), ...
                'tolerance', double(tolerance), ...
                'tolerancePercent', double(tolerancePercent), ...
                'minimumTolerance', double(minTolerance));
        end

        function [percent, minTolerance] = ...
                toleranceSettings(percent, hwConfig, field)
            axisName = [lower(field), 'Axis'];
            if ~isstruct(hwConfig) || ~isfield(hwConfig, 'plc') || ...
                    ~isfield(hwConfig.plc, axisName) || ...
                    ~isfield(hwConfig.plc.(axisName), 'fForceTolerance')
                error('PlotReference:MissingMinimumTolerance', ...
                    'Minimum force tolerance is missing for the %s axis.', ...
                    upper(field));
            end
            percent = double(percent);
            minTolerance = double( ...
                hwConfig.plc.(axisName).fForceTolerance);
            if ~isscalar(percent) || ~isfinite(percent) || ...
                    percent < 0 || percent > 100 || ...
                    ~isscalar(minTolerance) || ~isfinite(minTolerance) || ...
                    minTolerance < 0
                error('PlotReference:InvalidTolerancePercent', ...
                    ['Tolerance must be from 0 to 100%% and minimum force ' ...
                    'tolerance must be non-negative for the %s axis.'], ...
                    upper(field));
            end
        end
    end
end
