classdef PlotReferenceBuilder
    %PLOTREFERENCEBUILDER Builds force-target annotations for live plots.

    methods (Static)
        %% Preview construction and target grouping
        function preview = build(selectedTab, config, axisMode)
            % Build entries only for active axes and force-controlled endpoints.
            preview = struct( ...
                'testType', '', ...
                'X', PlotReferenceBuilder.emptyEntries(), ...
                'Y', PlotReferenceBuilder.emptyEntries());
            selectedTab = char(selectedTab);
            axes = TestCommandBuilder.axesForMode(axisMode);

            switch selectedTab
                case 'Pre-test'
                    preview.testType = 'pre';
                    for index = 1:numel(axes)
                        axis = axes{index};
                        field = lower(axis);
                        entries = PlotReferenceBuilder.emptyEntries();
                        if config.pre.preload.enabled
                            entries(end + 1) = ...
                                PlotReferenceBuilder.entry( ...
                                'Pre-test', 'Initial preload', ...
                                'preload', ...
                                config.pre.preload.value.(field), ...
                                config.pre.preload.forceTolerance.(field));
                        end
                        if config.pre.cyclic
                            entries(end + 1) = ...
                                PlotReferenceBuilder.entry( ...
                                'Pre-test', 'Pre-cycle load', ...
                                'load', config.pre.load.(field), ...
                                config.pre.cyclicForceTolerance.(field));
                            if ~config.pre.unloadToStart
                                entries(end + 1) = ...
                                    PlotReferenceBuilder.entry( ...
                                    'Pre-test', 'Pre-cycle unload', ...
                                    'unload', ...
                                    config.pre.unload.(field), ...
                                    config.pre.cyclicForceTolerance.(field));
                            end
                        end
                        preview.(axis) = entries;
                    end

                case 'Single test'
                    preview.testType = 'single';
                    for index = 1:numel(axes)
                        axis = axes{index};
                        field = lower(axis);
                        entries = PlotReferenceBuilder.emptyEntries();
                        tolerance = ...
                            config.single.forceTolerance.(field);
                        if strcmp(config.single.primaryMode, 'Force')
                            entries(end + 1) = ...
                                PlotReferenceBuilder.entry( ...
                                'Single test', 'Primary endpoint', ...
                                'primary', ...
                                config.single.primary.(field), tolerance);
                        end
                        if strcmp(config.single.secondaryMode, 'Force')
                            entries(end + 1) = ...
                                PlotReferenceBuilder.entry( ...
                                'Single test', 'Secondary endpoint', ...
                                'secondary', ...
                                config.single.secondary.(field), tolerance);
                        end
                        preview.(axis) = entries;
                    end

                case 'Cyclic test'
                    preview.testType = 'cyclic';
                    for index = 1:numel(axes)
                        axis = axes{index};
                        field = lower(axis);
                        entries = PlotReferenceBuilder.emptyEntries();
                        tolerance = ...
                            config.cyclic.forceTolerance.(field);
                        if strcmp(config.cyclic.loadMode, 'Force')
                            entries(end + 1) = ...
                                PlotReferenceBuilder.entry( ...
                                'Cyclic test', 'Load endpoint', ...
                                'load', ...
                                config.cyclic.load.(field), tolerance);
                        end
                        if strcmp(config.cyclic.unloadMode, 'Force')
                            entries(end + 1) = ...
                                PlotReferenceBuilder.entry( ...
                                'Cyclic test', 'Unload endpoint', ...
                                'unload', ...
                                config.cyclic.unload.(field), tolerance);
                        end
                        preview.(axis) = entries;
                    end
            end
        end

        function grouped = group(entries)
            % Merge identical bands while retaining every endpoint label.
            grouped = PlotReferenceBuilder.emptyEntries();
            for index = 1:numel(entries)
                entry = entries(index);
                match = [];
                for candidate = 1:numel(grouped)
                    if grouped(candidate).target == entry.target && ...
                            grouped(candidate).tolerance == entry.tolerance
                        match = candidate;
                        break;
                    end
                end
                if isempty(match)
                    grouped(end + 1) = entry;
                elseif ~contains( ...
                        [' / ', grouped(match).label, ' / '], ...
                        [' / ', entry.label, ' / '])
                    grouped(match).label = ...
                        [grouped(match).label, ' / ', entry.label];
                end
            end
        end

        function entries = emptyEntries()
            % Keep a stable empty schema so callers can concatenate entries.
            entries = struct( ...
                'phase', {}, 'label', {}, 'role', {}, ...
                'target', {}, 'tolerance', {});
        end
    end

    methods (Static, Access = private)
        %% Entry construction
        function value = entry(phase, label, role, target, tolerance)
            value = struct( ...
                'phase', char(phase), ...
                'label', char(label), ...
                'role', char(role), ...
                'target', double(target), ...
                'tolerance', double(tolerance));
        end
    end
end
