classdef PlcCommandValidator
    %PLCCOMMANDVALIDATOR Validates complete commands before any ADS writes.
    % It rejects missing fields, invalid scalar ranges, mismatched arrays,
    % and incompatible biaxial commands.

    methods (Static)
        %% Basic motion validation
        function basic(firstValue, secondValue, axisCfg)
            if ~isnumeric(firstValue) || ~isscalar(firstValue) || ...
                    ~isfinite(firstValue) || ~isnumeric(secondValue) || ...
                    ~isscalar(secondValue) || ~isfinite(secondValue) || ...
                    secondValue <= 0
                error('PLC:InvalidTrajectory', ...
                    ['Command values must be finite scalars and ' ...
                    'rate/duration positive.']);
            end
            if nargin >= 3
                PlcCommandValidator.forceTargets( ...
                    firstValue, axisCfg, 'Force target');
            end
        end

        function rate(value, axisCfg, label)
            if ~isnumeric(value) || ~isscalar(value) || ...
                    ~isfinite(value) || value == 0 || ...
                    abs(value) > double(axisCfg.fMaxVelocity)
                error('PLC:VelocityLimit', ...
                    '%s must be nonzero and at most %.6g.', ...
                    label, double(axisCfg.fMaxVelocity));
            end
        end

        %% Test-command validation
        function test(command, statusNow, axisCfg)
            required = {'includePreTest', 'preTestOnly', ...
                'preCycleCount', 'preloadEnabled', 'preloadValue', ...
                'preCycleLoadValue', 'preUnloadValue', ...
                'preUnloadToStart', 'preTestRate', ...
                'preTestForceTolerance', 'preloadHoldTime', ...
                'preCycleHoldTime', 'testRate', ...
                'singleForceTolerance', 'singleForceHoldTime', ...
                'cyclicForceTolerance', 'cyclicForceHoldTime', ...
                'cycleCount', ...
                'loadMode', 'loadValues', 'unloadMode', ...
                'unloadValues', 'stop1Mode', 'stop1Value', ...
                'stop2Mode', 'stop2Value', 'postTestMode'};
            deprecated = {'preLoadValue', 'forceDropPercent', ...
                'forceDropThreshold', 'preTestHoldTime', ...
                'forceHoldTime'};
            names = fieldnames(command);
            obsolete = intersect(names, deprecated, 'stable');
            if ~isempty(obsolete)
                error('PLC:DeprecatedCommandField', ...
                    'Test command contains deprecated field %s.', ...
                    obsolete{1});
            end
            for index = 1:numel(required)
                if ~isfield(command, required{index})
                    error('PLC:InvalidTestCommand', ...
                        'Test command is missing %s.', required{index});
                end
            end

            endpointFields = {'preloadHoldTime', 'preCycleHoldTime', ...
                'singleForceHoldTime', 'cyclicForceHoldTime'};
            for index = 1:numel(endpointFields)
                value = command.(endpointFields{index});
                if ~isnumeric(value) || ~isscalar(value) || ...
                        ~isfinite(value) || value < 0
                    error('PLC:InvalidTestCommand', ...
                        ['%s must be a finite, non-negative numeric ' ...
                        'scalar.'], endpointFields{index});
                end
            end
            toleranceFields = {'preTestForceTolerance', ...
                'singleForceTolerance', 'cyclicForceTolerance'};
            for index = 1:numel(toleranceFields)
                value = command.(toleranceFields{index});
                if ~isnumeric(value) || ~isscalar(value) || ...
                        ~isfinite(value) || value < -100
                    error('PLC:InvalidTestCommand', ...
                        '%s must be absolute N or an encoded percentage.', ...
                        toleranceFields{index});
                end
            end
            if ~PlcCommandValidator.isIntegerInRange( ...
                    command.postTestMode, 0, 4)
                error('PLC:InvalidTestCommand', ...
                    'Invalid post-test mode.');
            end
            if command.postTestMode == 1 && ...
                    ~statusNow.savedPositionValid
                error('PLC:NoSavedPosition', ...
                    'Return-to-saved requires a saved PLC position.');
            end
            if command.preTestOnly && ~command.includePreTest
                error('PLC:InvalidTestCommand', ...
                    'Pre-test-only commands must include a pre-test.');
            end
            if command.includePreTest
                preValues = [command.preloadValue, ...
                    command.preCycleLoadValue, command.preUnloadValue, ...
                    command.preTestRate];
                if ~PlcCommandValidator.isIntegerInRange( ...
                        command.preCycleCount, 0, 50) || ...
                        any(~isfinite(preValues)) || ...
                        command.preTestRate <= 0
                    error('PLC:InvalidTestCommand', ...
                        'Invalid force pre-conditioning values.');
                end
            end
            if nargin >= 3 && command.includePreTest && ...
                    (command.preloadEnabled || command.preCycleCount > 0)
                PlcCommandValidator.rate( ...
                    command.preTestRate, axisCfg, 'Pre-test speed');
                preForceTargets = [];
                if command.preloadEnabled
                    preForceTargets(end + 1) = command.preloadValue;
                end
                if command.preCycleCount > 0
                    preForceTargets(end + 1) = ...
                        command.preCycleLoadValue;
                    if ~command.preUnloadToStart
                        preForceTargets(end + 1) = ...
                            command.preUnloadValue;
                    end
                end
                PlcCommandValidator.forceTargets( ...
                    preForceTargets, axisCfg, 'Pre-test force target');
            end
            if command.preTestOnly
                return;
            end
            if ~isnumeric(command.testRate) || ...
                    ~isscalar(command.testRate) || ...
                    ~isfinite(command.testRate) || command.testRate <= 0
                error('PLC:InvalidTestCommand', ...
                    'Movement speed must be positive.');
            end
            if nargin >= 3
                PlcCommandValidator.rate( ...
                    command.testRate, axisCfg, 'Test speed');
            end
            if ~PlcCommandValidator.isIntegerInRange( ...
                    command.cycleCount, 0, 50)
                error('PLC:InvalidTestCommand', ...
                    'Cycle count must be an integer from 0 to 50.');
            end
            if command.cycleCount > 0
                if ~ismember(command.loadMode, [1, 2]) || ...
                        ~ismember(command.unloadMode, [1, 2])
                    error('PLC:InvalidTestCommand', ...
                        ['Load and unload modes must be displacement ' ...
                        'or force.']);
                end
                if numel(command.loadValues) ~= command.cycleCount || ...
                        numel(command.unloadValues) ~= ...
                        command.cycleCount || ...
                        any(~isfinite(command.loadValues)) || ...
                        any(~isfinite(command.unloadValues))
                    error('PLC:InvalidTestCommand', ...
                        ['Load/unload arrays must match the ' ...
                        'cycle count.']);
                end
            else
                stopValues = [command.stop1Value, command.stop2Value];
                if ~ismember(command.stop1Mode, [1, 2]) || ...
                        ~ismember(command.stop2Mode, [0, 1, 2, 3]) || ...
                        any(~isfinite(stopValues)) || ...
                        (command.stop2Mode == 3 && ...
                        (command.stop2Value <= 0 || command.stop2Value > 100))
                    error('PLC:InvalidTestCommand', ...
                        'Invalid single-test endpoint configuration.');
                end
            end
            if nargin >= 3
                if command.stop2Mode == 3 && ...
                        double(axisCfg.fForceTolerance) <= 0
                    error('PLC:InvalidConfiguration', ...
                        ['Rupture detection requires a positive hardware ' ...
                        'force tolerance for its arming threshold.']);
                end
                forceTargets = [];
                if command.cycleCount > 0
                    if command.loadMode == 2
                        forceTargets = [forceTargets, command.loadValues];
                    end
                    if command.unloadMode == 2
                        forceTargets = [forceTargets, command.unloadValues];
                    end
                else
                    if command.stop1Mode == 2
                        forceTargets(end + 1) = command.stop1Value;
                    end
                    if command.stop2Mode == 2
                        forceTargets(end + 1) = command.stop2Value;
                    end
                end
                PlcCommandValidator.forceTargets( ...
                    forceTargets, axisCfg, 'Force endpoint');
            end
        end

        %% Biaxial command and hardware-setting validation
        function biaxial(commandX, commandY)
            fields = {'includePreTest', 'preTestOnly', ...
                'preCycleCount', 'preloadEnabled', ...
                'preUnloadToStart', 'cycleCount', 'postTestMode'};
            for index = 1:numel(fields)
                field = fields{index};
                if ~isequal(commandX.(field), commandY.(field))
                    error('PLC:InvalidBiaxialCommand', ...
                        ['Biaxial commands must use matching %s ' ...
                        'settings.'], field);
                end
            end
        end

        function axisConfig(axisCfg)
            required = {'fTenzoCons', 'fTenzoOffset', 'fKp', 'fKi', ...
                'fIntegralLimit', 'fForceTolerance', 'fMaxVelocity', ...
                'fMaxForce', 'fForceReliefDistance', ...
                'fForceReliefVelocity'};
            PlcCommandValidator.requireExactFields( ...
                axisCfg, required, 'PLC axis configuration');
            values = cellfun(@(name) double(axisCfg.(name)), required);
            if any(~isfinite(values)) || axisCfg.fTenzoCons == 0 || ...
                    axisCfg.fKp < 0 || axisCfg.fKi < 0 || ...
                    (axisCfg.fKp == 0 && axisCfg.fKi == 0) || ...
                    axisCfg.fIntegralLimit < 0 || ...
                    axisCfg.fForceTolerance <= 0 || ...
                    axisCfg.fMaxVelocity <= 0 || ...
                    axisCfg.fMaxForce <= 0 || ...
                    axisCfg.fForceReliefDistance <= 0 || ...
                    axisCfg.fForceReliefVelocity <= 0 || ...
                    axisCfg.fForceReliefVelocity > axisCfg.fMaxVelocity
                error('PLC:InvalidConfiguration', ...
                    'Hardware configuration contains invalid values.');
            end
        end

        function requireExactFields(value, required, path)
            if ~isstruct(value) || ~isscalar(value)
                error('PLC:InvalidConfiguration', ...
                    '%s must be one object.', path);
            end
            names = fieldnames(value);
            missing = setdiff(required, names, 'stable');
            unknown = setdiff(names, required, 'stable');
            if ~isempty(missing)
                error('PLC:InvalidConfiguration', ...
                    '%s is missing %s.', path, missing{1});
            end
            if ~isempty(unknown)
                error('PLC:InvalidConfiguration', ...
                    '%s contains unsupported field %s.', ...
                    path, unknown{1});
            end
        end
    end

    methods (Static, Access = private)
        function forceTargets(values, axisCfg, label)
            values = values(:);
            if any(~isfinite(values)) || ...
                    any(abs(values) >= double(axisCfg.fMaxForce))
                error('PLC:ForceLimit', ...
                    '%s must remain below the configured %.6g limit.', ...
                    label, double(axisCfg.fMaxForce));
            end
        end

        function valid = isIntegerInRange(value, minimum, maximum)
            valid = isscalar(value) && isfinite(value) && ...
                value == round(value) && value >= minimum && ...
                value <= maximum;
        end
    end
end
