<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="F_ValidateAdsSettings" Id="{bf9fdd3b-fb86-42e9-91dd-97aa19a1749f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_ValidateAdsSettings : BOOL
VAR_INPUT
	stValue : ST_Settings;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_ValidateAdsSettings :=
	(stValue.fTenzoCons <> 0) AND
	(stValue.fIntegralLimit >= 0) AND
	(stValue.fForceTolerance >= 0) AND
	(stValue.fMaxVelocity > 0) AND
	(stValue.fMaxForce > 0) AND
	(stValue.fForceReliefDistance > 0) AND
	(stValue.fForceReliefVelocity > 0) AND
	(stValue.fTenzoCons = stValue.fTenzoCons) AND
	(stValue.fTenzoOffset = stValue.fTenzoOffset) AND
	(stValue.fKp = stValue.fKp) AND
	(stValue.fKi = stValue.fKi) AND
	(stValue.fIntegralLimit = stValue.fIntegralLimit) AND
	(stValue.fForceTolerance = stValue.fForceTolerance) AND
	(stValue.fMaxVelocity = stValue.fMaxVelocity) AND
	(stValue.fMaxForce = stValue.fMaxForce) AND
	(stValue.fForceReliefDistance = stValue.fForceReliefDistance) AND
	(stValue.fForceReliefVelocity = stValue.fForceReliefVelocity);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
