function verifyGeneratedTmc(tmcFile)
% Run after a TwinCAT build to verify generated ADS metadata version 3.
if nargin < 1
    repo = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    tmcFile = fullfile(repo, 'MAINplc', 'main program.tmc');
end
text = fileread(tmcFile);
required = {'nInterfaceVersion', 'bSavedPositionValid', ...
    'bRestorePosition', 'fRestoreVelocity', 'bIncludePreTest', ...
    'bPreTestOnly', 'nPreCycleCount', 'bPreloadEnabled', ...
    'fPreloadValue', 'fPreLoadValue', 'fPreUnloadValue', ...
    'bPreUnloadToStart', 'fPreTestRate', 'fPreTestHoldTime', ...
    'fTestRate', 'fForceHoldTime', 'fForceDropPercent', ...
    'fForceDropThreshold', 'nCycleCount', 'nLoadMode', ...
    'fLoadValues', 'nUnloadMode', 'fUnloadValues', 'nStop1Mode', ...
    'fStop1Value', 'nStop2Mode', 'fStop2Value', 'nPostTestMode', ...
    'fForceReliefDistance', 'fForceReliefVelocity'};
missing = {};
for index = 1:numel(required)
    marker = ['<Name>', required{index}, '</Name>'];
    if ~contains(text, marker)
        missing{end + 1} = required{index}; %#ok<AGROW>
    end
end
if ~isempty(missing)
    error('PLC:TmcOutOfDate', ...
        ['Generated TMC is stale. Build the TwinCAT project; missing ' ...
        'interface fields: %s'], strjoin(missing, ', '));
end
arrayFields = {'fDistances', 'fVelocities', ...
    'fLoadValues', 'fUnloadValues'};
for index = 1:numel(arrayFields)
    expression = ['<Name>', arrayFields{index}, '</Name>.*?', ...
        '<ArrayInfo><LBound>1</LBound><Elements>100</Elements>'];
    if isempty(regexp(text, expression, 'once'))
        error('PLC:TmcArraySize', ...
            '%s is not generated as a 100-entry array.', ...
            arrayFields{index});
    end
end
fprintf('Generated TwinCAT symbols match interface version 3.\n');
end
