function verifyGeneratedTmc(tmcFile)
% Run after a TwinCAT build to verify generated ADS metadata version 6.
if nargin < 1
    repo = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    tmcFile = fullfile(repo, 'TwinCat', 'AortyPLC', ...
        'main program', 'main program.tmc');
end
text = fileread(tmcFile);
required = {'nInterfaceVersion', 'bSavedPositionValid', ...
    'nSystemStatus', 'fMoveDistance', 'fMoveVelocity', ...
    'fTargetForce', 'fForceDuration', ...
    'bRestorePosition', 'fRestoreVelocity', 'bIncludePreTest', ...
    'bPreTestOnly', 'nPreCycleCount', 'bPreloadEnabled', ...
    'fPreloadValue', 'fPreCycleLoadValue', 'fPreUnloadValue', ...
    'bPreUnloadToStart', 'fPreTestRate', ...
    'fPreTestForceTolerance', 'fPreloadHoldTime', ...
    'fPreCycleHoldTime', 'fTestRate', ...
    'fSingleForceTolerance', 'fSingleForceHoldTime', ...
    'fCyclicForceTolerance', 'fCyclicForceHoldTime', ...
    'nCycleCount', 'nLoadMode', ...
    'fLoadValues', 'nUnloadMode', 'fUnloadValues', 'nStop1Mode', ...
    'fStop1Value', 'nStop2Mode', 'fStop2Value', 'nPostTestMode', ...
    'fForceReliefDistance', 'fForceReliefVelocity', ...
    'bStartBiaxialTest'};
missing = {};
for index = 1:numel(required)
    if strcmp(required{index}, 'bStartBiaxialTest')
        markers = {'<Name>bStartBiaxialTest</Name>', ...
            '<Name>MAIN.bStartBiaxialTest</Name>'};
    else
        markers = {['<Name>', required{index}, '</Name>']};
    end
    if ~any(cellfun(@(marker) contains(text, marker), markers))
        missing{end + 1} = required{index}; %#ok<AGROW>
    end
end
if ~isempty(missing)
    error('PLC:TmcOutOfDate', ...
        ['Generated TMC is stale. Build the TwinCAT project; missing ' ...
        'interface fields: %s'], strjoin(missing, ', '));
end
arrayFields = {'fLoadValues', 'fUnloadValues'};
for index = 1:numel(arrayFields)
    expression = ['<Name>', arrayFields{index}, '</Name>.*?', ...
        '<ArrayInfo><LBound>1</LBound><Elements>50</Elements>'];
    if isempty(regexp(text, expression, 'once'))
        error('PLC:TmcArraySize', ...
            '%s is not generated as a 50-entry array.', ...
            arrayFields{index});
    end
end
if isempty(regexp(text, ...
        '<Name>nInterfaceVersion</Name>.*?<Default><Value>6</Value></Default>', ...
        'once'))
    error('PLC:TmcInterfaceVersion', ...
        'Generated TMC does not declare interface version 6.');
end
fprintf('Generated TwinCAT symbols match interface version 6.\n');
end
